DROP TABLE Visit;
CREATE TABLE Visit(
	Id INTEGER PRIMARY KEY NOT NULL,
	MAC CHAR(17) NOT NULL,
	FirstSeen DATETIME NOT NULL,
	LastSeen DATETIME NOT NULL,
	Pings INTEGER NOT NULL
);
CREATE INDEX VisitMACIndex ON Visit (MAC);

DROP TABLE MACWhitelist;
CREATE TABLE MACWhitelist(
	MAC CHAR(17) PRIMARY KEY NOT NULL,
	Note VARCHAR(60) NOT NULL
);
